/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JinNang: typeof import('./src/components/JinNang.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockList: typeof import('./src/components/StockList.vue')['default']
    VanCol: typeof import('vant/es')['Col']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanRow: typeof import('vant/es')['Row']
    VanTag: typeof import('vant/es')['Tag']
  }
}
