/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MyFollow: typeof import('./src/components/MyFollow.vue')['default']
    PoolDetail: typeof import('./src/components/PoolDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockPool: typeof import('./src/components/StockPool.vue')['default']
    Trade: typeof import('./src/components/Trade.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanCol: typeof import('vant/es')['Col']
    VanList: typeof import('vant/es')['List']
    VanRow: typeof import('vant/es')['Row']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
